VID/VID/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('login.urls')),
    path('', include('recetario.urls')),
]
if settings.DEBUG:
    urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [] + static(settings.MEDIA_URL)

VID/recetario/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url, include
from django.contrib import admin
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('busqueda/', resBusqueda, name='resBusqueda'),
    path('nosotros/', resNosotros, name='resNosotros'),
    path('registro/', resRegistro, name='resRegistro'),
    path('crear_receta/', crearReceta, name='crearReceta'),
    path('regReceta/', guardarReceta, name='guardarReceta'),
    path('explorar/', resExplorar, name='resExplorar'),
    path('mostrar/<id>', mostrarReceta, name='mostrarReceta'),
    path('misRecetas/', misRecetas, name='misRecetas'),
    path('eliminar/<id>', eliminarReceta, name='eliminarReceta'),
    path('actualizar/<id>', actualizarReceta, name='actualizarReceta'),
    path('finActualizarReceta/<id>', finActualizarReceta, name='finActualizarReceta'),
]

urlpatterns += staticfiles_urlpatterns()

VID/recetario/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class recetas(models.Model):
    nombre = models.TextField()
    descripcion = models.TextField()
    propietario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    imagenMuestra = models.ImageField(upload_to ='imgRecetas/', blank=True, null=True)

class ingredientesReceta(models.Model):
    receta = models.ForeignKey(recetas, on_delete=models.CASCADE)
    ingredientes = models.TextField()

class imgReceta(models.Model):
    receta = models.ForeignKey(recetas, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to ='imgRecetas/', blank=True, null=True)

class pasosReceta(models.Model):
    receta = models.ForeignKey(recetas, on_delete=models.CASCADE)
    paso = models.TextField()
    pasoNumer = models.SmallIntegerField()

VID/recetario/views.py
from django.shortcuts import render, redirect
from .models import *
# Create your views here.

def resBusqueda(request):
    buscar = request.POST['buscar']
    #Consulta like SQL... es nombreDelCampo__contains=valorABuscar
    resultado = recetas.objects.filter(nombre__contains=buscar)
    return render(request, 'busqueda.html', {'resultado': resultado,
                                             'buscar': buscar})                                          


def mostrarReceta(request, id):
    receta = recetas.objects.get(id=id)
    ingredientes = ingredientesReceta.objects.filter(receta=id)
    pasos = pasosReceta.objects.filter(receta=id).order_by('pasoNumer')
    return render(request, 'mostrar.html', {'receta':receta,
                                            'ingredientes': ingredientes,
                                            'pasos':pasos})

def resExplorar(request):
    expReceta = recetas.objects.all()   
    return render(request, 'explorar.html',{'expReceta':expReceta})                                          

def resNosotros(request):
    return render(request, 'nosotros.html')

def resRegistro(request):
    return render(request, 'registro.html')

def crearReceta(request):
    if request.user.is_authenticated:
        return render(request, 'crearReceta.html')
    else:
        return redirect('login')

def guardarReceta(request):
    if request.method == 'POST':
        #Guardar datos generales de receta
        recetaGeneral = recetas(nombre=request.POST['nombre'],
                                descripcion=request.POST['descripcion'], propietario=request.user,
                                imagenMuestra=request.FILES['imagenMuestra'])
        recetaGeneral.save()
        ######Guardar imagenes extra de receta
        #Iterador para guardar cada una de las imagenes
        iterador = 1
        #Esta "bandera" se utiliza para que en cuanto ya no encuentre un siguiente elemento deje de intentar guardar
        bandera = True
        #Cilo para guardar las imagenes
        while bandera:
            #Guarda imagen
            try:
                img = imgReceta(receta=recetaGeneral, imagen=request.FILES["image" + str(iterador)])
                img.save()
                #Incrementa el iterador para obtener la siguiente imagen
                iterador += 1
            #Si falla el intento de guardar, la "bandera" cambia a false para que el ciclo se detenga
            except:
                bandera = False
        ######Guardar pasos de receta
        #Iterador para guardar cada una de los pasos
        iterador = 1
        #Esta "bandera" se utiliza para que en cuanto ya no encuentre un siguiente elemento deje de intentar guardar
        bandera = True
        #Cilo para guardar los pasos
        while bandera:
            #Guarda el paso de la receta
            paso = pasosReceta(receta=recetaGeneral, paso=request.POST["paso" + str(iterador)], pasoNumer=iterador)
            paso.save()
            # Incrementa el iterador para obtener el siguiente paso
            iterador += 1
            # Se intenta mostrar el contenido del siguiente paso a guardar
            try:
                print(request.POST["paso" + str(iterador)])
            except:
                # Si falla el intento la "bandera" cambia a false para que el ciclo se detenga
                bandera = False
        ######Guardar recetario de receta
        #Iterador para guardar cada una de los ingredientes
        iterador = 1
        #Esta "bandera" se utiliza para que en cuanto ya no encuentre un siguiente elemento deje de intentar guardar
        bandera = True
        #Cilo para guardar los ingredientes
        while bandera:
            #Guarda el paso de la receta
            ingrediente = ingredientesReceta(receta=recetaGeneral, ingredientes=request.POST["ingrediente" + str(iterador)])
            ingrediente.save()
            # Incrementa el iterador para obtener el siguiente paso
            iterador += 1
            # Se intenta mostrar el contenido del siguiente paso a guardar
            try:
                print(request.POST["ingrediente" + str(iterador)])
            except:
                # Si falla el intento la "bandera" cambia a false para que el ciclo se detenga
                bandera = False
        #Redirige a la pantalla principal
        return redirect('index')
    #Redirige a la página de crear receta
    return redirect('crearReceta')

def misRecetas(request):
    receta = recetas.objects.filter(propietario=request.user.id)
    return render(request, 'misRecetas.html', {'recetas': receta})

def eliminarReceta(request, id):
    recetas.objects.filter(id=id).delete()
    return redirect('misRecetas')

def actualizarReceta(request, id):
    receta = recetas.objects.get(id=id, propietario=request.user.id)

    ingredientes = ingredientesReceta.objects.filter(receta=id)
    listaIngredientes = ""
    for element in ingredientes:
        listaIngredientes += element.ingredientes + ","
    cantIngredientes = ingredientes.count()

    pasos = pasosReceta.objects.filter(receta=id).order_by('pasoNumer')
    listaPasos = ""
    for element in pasos:
        listaPasos += element.paso + ","
    cantPasos = pasos.count()
    '''
    img = imgReceta.objects.filter(receta=id)
    listaImg = ""
    for element in pasos:
        listaImg += img.imagen + ","
    cantImg = img.count()'''
    return render(request, 'actualizarReceta.html', {'receta': receta,
                                                     'ingredientes': listaIngredientes,
                                                     'cantIngredientes': cantIngredientes,
                                                     'pasos': listaPasos,
                                                     'cantPasos': cantPasos,
                                                     #'img': listaImg,
                                                     #'cantImg': cantImg
                                                     })

def finActualizarReceta(request, id):
    if request.method == 'POST':
        #Actualiza datos generales de receta
        recetas.objects.filter(id=id).update(nombre=request.POST['nombre'],
                                descripcion=request.POST['descripcion'])
        recetaGeneral = recetas.objects.get(id=id)

        ######Actualizar pasos de receta
        #Borramos los pasos anteriores
        pasosReceta.objects.filter(receta=id).delete()
        #Iterador para guardar cada uno de los pasos nuevos
        iterador = 1
        #Esta "bandera" se utiliza para que en cuanto ya no encuentre un siguiente elemento deje de intentar guardar
        bandera = True
        #Cilo para guardar los pasos
        while bandera:
            #Guarda el paso de la receta
            paso = pasosReceta(receta=recetaGeneral, paso=request.POST["paso" + str(iterador)], pasoNumer=iterador)
            paso.save()
            # Incrementa el iterador para obtener el siguiente paso
            iterador += 1
            # Se intenta mostrar el contenido del siguiente paso a guardar
            try:
                print(request.POST["paso" + str(iterador)])
            except:
                # Si falla el intento la "bandera" cambia a false para que el ciclo se detenga
                bandera = False

        ingredientesReceta.objects.filter(receta=id).delete()
        ######Guardar recetario de receta
        #Iterador para guardar cada una de los ingredientes
        iterador = 1
        #Esta "bandera" se utiliza para que en cuanto ya no encuentre un siguiente elemento deje de intentar guardar
        bandera = True
        #Cilo para guardar los ingredientes
        while bandera:
            #Guarda el paso de la receta
            ingrediente = ingredientesReceta(receta=recetaGeneral, ingredientes=request.POST["ingrediente" + str(iterador)])
            ingrediente.save()
            # Incrementa el iterador para obtener el siguiente paso
            iterador += 1
            # Se intenta mostrar el contenido del siguiente paso a guardar
            try:
                print(request.POST["ingrediente" + str(iterador)])
            except:
                # Si falla el intento la "bandera" cambia a false para que el ciclo se detenga
                bandera = False
    #Redirige a la página de crear receta
    return redirect('misRecetas')

VID/recetario/templates/actualizarReceta.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<form method="post" action="{% url 'finActualizarReceta' receta.id %}" class="p-2 m-2 p-4 bg-white" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mx-auto">
        <div class="col-12">
            <h2>Actualiza: {{receta.nombre}} </h2>
        </div>
        <div class="row mx-auto align-items-center mt-2 mb-3">
            <img src="{% static 'img\Vegetarianos.png' %}" class="rounded mx-auto d-block" width="100" height="100">
            <h4 class="font-weight-bold" style="color: #249E16;">VID matchRecipes</h4>
        </div>
    </div>
    <div class="row justify-content-around">

        <div class="col-5">
            <div class="row mx-auto">
                <div class="col-12">
                    <div class="form-group">
                        <input class="form-control text-center" type="text" name="nombre" id="id_nombre" placeholder="Nombre de receta" required value="{{receta.nombre}}">
                    </div>
                </div>
            </div>

            <div class="row mx-auto">
                <div class="col-12">
                    <div class="form-group">
                        <input class="form-control text-center" type="text" name="descripcion" id="id_descripcion" placeholder="Descripción corta" required value="{{receta.descripcion}}">
                    </div>
                </div>
            </div>

            <div class="row mx-auto">
                <div class="col-12">
                    <label>Ingredientes:</label>
                    <div id="ingrediente">
                        <div class="form-group" id="div_ingrediente0">
                            <input class="form-control text-center" type="text" name="ingrediente1" id="id_ingrediente"
                            placeholder="Ingrediente 1" required>
                        </div>
                    </div>
                </div>
            </div>

                <!--div class="row mx-auto">
                    <div class="col-12 form-group">
                        <div class="">
                            <input type="file" class="" name="imagenMuestra" id="id_imagenMuestra">
                            <label class="" for="id_imagenMuestra">Selecciona una imagen</label>
                        </div>
                    </div>
                </div-->

            <div class="row mx-auto">
                <div class="col-12 form-group">
                    <div id="images">

                    </div>
                </div>
            </div>
        </div>


        <div class="col-1">
            <div class="row d-flex justify-content-center" style="margin-top: 110px; margin-left: -110px;" >
                <div class="form-group">
                    <button type="button" class="btn btn-outline-success" onclick="addIngrediente();" id="addIng">+</button>
                    <button type="button" class="btn btn-outline-danger" onclick="remIngrediente();" id="remIng">-</button>
                </div>
            </div>
            <!--div id="botonesImagen" class="row d-flex justify-content-center" style="margin-top: 0px; margin-left: -110px;" >
                <div class="form-group">
                    <button type="button" class="btn btn-outline-success" onclick="add();" id="addImg">+</button>
                    <button type="button" class="btn btn-outline-danger" onclick="rem();" id="remImg">-</button>
                </div>
            </div-->
        </div>




        <div class="col-5">
            <div class="row mx-auto">
                <div class="col-12">
                    <div id="pasos">
                        <div class="form-group" id="div_paso0">
                            <label class="mr-2">Paso 1:</label>
                            <textarea class="form-control" name="paso1" id="id_paso1" rows="2" required></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="row d-flex justify-content-center">
            <div class="" style="margin-top: 55px; margin-left: -10px;" >
                <button type="button" class="btn btn-outline-success" onclick="addpaso();" id="addPaso">+</button>
                <button type="button" class="btn btn-outline-danger" onclick="rempaso();" id="remPaso">-</button>
            </div>
        </div>

    </div>

    {% if user.is_authenticated %}

    <div class="row d-flex justify-content-center mb-5">
        <button type="submit" class="btn btn-lg text-white pl-5 pr-5" name="button" style="background-color: #249E16;">Actualizar receta</button>
    </div>

    {% else %}
    <div class="text-center">
        <a style="font-size: large;" href="{% url 'login' %}">Iniciar sesión</a>
    </div>
    {% endif %}
</form>
{% endblock %}

{% block js %}
<script type='text/javascript'>
    //var num = {{cantImg}};
    var numIng = {{cantIngredientes}};
    var numPasos = {{cantPasos}};
    var pasos = '{{pasos}}';
    var pasosSplit = pasos.split(',');

    var ingredientes = '{{ingredientes}}';
    var ingredientesSplit = ingredientes.split(',');

    //ctrlImagenes();
    ctrlIngredientes();
    ctrlPasos();

    /*function add(){ num++; ctrlImagenes(); }
    function rem(){ if(num != 0){num--;} ctrlImagenes(); }*/
    function addIngrediente(){
        actArrayIngredientes();
        numIng++;
        ctrlIngredientes(); }
    function remIngrediente(){
        actArrayIngredientes();
        if(numIng != 1){
            numIng--;
            ingredientesSplit.pop();}
        ctrlIngredientes(); }
    function addpaso(){
        actArrayPasos();
        numPasos++;
        ctrlPasos(); }
    function rempaso(){
        actArrayPasos();
        if(numPasos != 1){
            numPasos--;
            pasosSplit.pop();}
        ctrlPasos(); }

    /*function ctrlImagenes(){
        var container = document.getElementById("images");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<num;i++){
            var newDiv = document.createElement('div');
            newDiv.className += "custom-file mb-1";
            newDiv.id = "div_image" + (i+1);
            container.appendChild(newDiv);

            var newLabel = document.createElement('label');
            //newLabel.className += "custom-file-label";
            newLabel.innerHTML = "Imagen extra";
            newLabel.name = "image" + i;
            newDiv.appendChild(newLabel);

            var input = document.createElement("input");
            input.className += "custom-file-input";
            input.type = "file";
            input.name = "image" + (i+1);
            input.id = "id_image" + (i+1);
            input.required = 'required';
            //input.accept = "image/*";
            newDiv.appendChild(input);
            //newDiv.appendChild(document.createElement("br"));
        }
    }*/

    function actArrayPasos(){
        pasosSplit = [];
        var name = ""
        for(i=0; i<numPasos; i++){
            name = "id_paso"+(i+1);
            var data = document.getElementById(name).value;
            pasosSplit.push(data);
        }
    }
    actArrayPasos();

    function ctrlPasos(){
        var container = document.getElementById("pasos");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<numPasos;i++){
            var newDiv = document.createElement('div');
            newDiv.className += "form-group";
            newDiv.id = "div_paso" + (i+1);
            container.appendChild(newDiv);

            var newLabel = document.createElement('label');
            newLabel.className += "mr-2";
            newLabel.innerHTML = "Paso " + (i+1) + ":";
            newLabel.name = "image" + i;
            newDiv.appendChild(newLabel);

            var input = document.createElement("textarea");
            input.className += "form-control";
            input.name = "paso" + (i+1);
            input.id = "id_paso" + (i+1);
            input.rows = "2";
            input.required = 'required';
            if(pasosSplit[i]==undefined){
                input.value = '';
            }else{
                input.value = pasosSplit[i];
            }
            newDiv.appendChild(input);
            //newDiv.appendChild(document.createElement("br"));
        }
    }

    function actArrayIngredientes(){
        ingredientesSplit = [];
        var name = ""
        for(i=0; i<numIng; i++){
            name = "id_ingrediente"+(i+1);
            var data = document.getElementById(name).value;
            ingredientesSplit.push(data);
        }
    }
    actArrayIngredientes();

    function ctrlIngredientes(){
        var container = document.getElementById("ingrediente");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<numIng;i++){
            var newDiv = document.createElement('div');
            newDiv.className += "form-group";
            newDiv.id = "div_ingrediente" + (i+1);
            container.appendChild(newDiv);

            var input = document.createElement("input");
            input.className += "form-control text-center";
            input.name = "ingrediente" + (i+1);
            input.id = "id_ingrediente" + (i+1);
            input.placeholder = "Ingrediente" + (i+1);
            input.rows = "1";
            input.required = 'required';
            if(ingredientesSplit[i]==undefined){
                input.value = '';
            }else{
                input.value = ingredientesSplit[i];
            }
            newDiv.appendChild(input);
            console.log(ingredientesSplit[i]);
            //newDiv.appendChild(document.createElement("br"));
        }
    }
</script>
{% endblock %}

VID/recetario/templates/busqueda.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <h4 class="">Resultado de la busqueda: {{ buscar }} </h4>
    <div class="row m-4">
        {% if resultado.count == 0 %}
            <p>No hay resultados que coincidan con tu búsqueda</p>
        {% else %}
            {% for element in resultado %}
            <div class="card float-left col-3 border-0 mt-3">
                <img src="{{ MEDIA_URL }}{{ element.imagenMuestra }}" class="card-img-top" height="200px" width="200px" alt="...">
                <div class="card-body" style="background-color: #249E16;">
                    <h5 class="card-title text-white">{{ element.nombre }}</h5>
                    <p class="card-text text-white">{{ element.descripcion }}</p>
                    <a href="{% url 'mostrarReceta' element.id %}" class="btn btn-light float-right">Ver receta</a>
              </div>
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

VID/recetario/templates/crearReceta.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<form method="post" action="{% url 'guardarReceta' %}" class="p-2 m-2 p-4 bg-white" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mx-auto">
        <div class="col-12">
            <h2>¡Crea tu receta!</h2>
        </div>
        <div class="row mx-auto align-items-center mt-2 mb-3">
            <img src="{% static 'img\Vegetarianos.png' %}" class="rounded mx-auto d-block" width="100" height="100">
            <h4 class="font-weight-bold" style="color: #249E16;">VID matchRecipes</h4>
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="row">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <td>
                            <div class="form-group">
                                <input class="form-control text-center" type="text" name="descripcion" id="id_descripcion" placeholder="Descripción corta" required>
                            </div>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            <label>Ingredientes:</label>
                            <div id="ingrediente">
                                <div class="form-group" id="div_ingrediente0">
                                    <input class="form-control text-center" type="text" name="ingrediente1" id="id_ingrediente1"
                                    placeholder="Ingrediente 1" required>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <button type="button" class="btn btn-outline-success" onclick="addIngrediente();" id="addIng">+</button>
                                <button type="button" class="btn btn-outline-danger" onclick="remIngrediente();" id="remIng">-</button>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="file" class="" name="imagenMuestra" id="id_imagenMuestra" accept="image/*" required>
                            <label class="" for="id_imagenMuestra">Selecciona una imagen</label>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            <div id="images">

                            </div>
                        </td>
                        <td>
                            <button type="button" class="btn btn-outline-success" onclick="add();" id="addImg">+</button>
                            <button type="button" class="btn btn-outline-danger" onclick="rem();" id="remImg">-</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-5">
            <div class="row mx-auto">
                <div class="col-12">
                    <div id="pasos">
                        <div class="form-group" id="div_paso0">
                            <label class="mr-2">Paso 1:</label>
                            <textarea class="form-control" name="paso1" id="id_paso1" rows="2" required></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        
        <div class="row d-flex justify-content-center">
            <div class="" style="margin-top: 55px; margin-left: -10px;" >
                <button type="button" class="btn btn-outline-success" onclick="addpaso();" id="addPaso">+</button>
                <button type="button" class="btn btn-outline-danger" onclick="rempaso();" id="remPaso">-</button>
            </div>
        </div>

    </div>

    <div class="row d-flex justify-content-center mb-5">
        <button type="submit" class="btn btn-lg text-white pl-5 pr-5" name="button" style="background-color: #249E16;">Registrar receta</button>
    </div>
</form>
{% endblock %}

{% block js %}
<script type='text/javascript'>
    var num = 0;
    var numIng = 1;
    var numPasos = 1;

    function add(){
        //actArrayImagenes();
        num++;
        ctrlImagenes(); }
    function rem(){
        if(num != 0){num--;}
        ctrlImagenes(); }
    function addIngrediente(){
        actArrayIngredientes();
        numIng++;
        ctrlIngredientes(); }
    function remIngrediente(){
        if(numIng != 1){ numIng--;}
        ctrlIngredientes(); }
    function addpaso(){
        actArrayPasos();
        numPasos++;
        ctrlPasos(); }
    function rempaso(){
        if(numPasos != 1){numPasos--;}
        ctrlPasos(); }

    /*var arrayImagenes = [];
    function actArrayImagenes(){
        arrayImagenes = [];
        var name = ""
        for(i=0; i<num; i++){
            name = "id_image"+(i+1);
            var data = document.getElementById(name).value;
            arrayImagenes.push(data);
        }
        alert(arrayImagenes);
    }
    actArrayImagenes();*/

    function ctrlImagenes(){
        var container = document.getElementById("images");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<num;i++){
            var newDiv = document.createElement('div');
            //newDiv.className += "custom-file mb-1";
            newDiv.id = "div_image" + (i+1);
            container.appendChild(newDiv);

            var newLabel = document.createElement('label');
            newLabel.className += "mr-2";
            newLabel.innerHTML = "Imagen " + (i+1) + " extra: ";
            newLabel.name = "image" + i;
            newDiv.appendChild(newLabel);

            var input = document.createElement("input");
            //input.className += "custom-file-input";
            input.type = "file";
            input.name = "image" + (i+1);
            input.id = "id_image" + (i+1);
            input.required = 'required';
            input.accept = "image/*";
            newDiv.appendChild(input);
            //newDiv.appendChild(document.createElement("br"));
        }
    }

    var arrayPasos = [];
    function actArrayPasos(){
        arrayPasos = [];
        var name = ""
        for(i=0; i<numPasos; i++){
            name = "id_paso"+(i+1);
            var data = document.getElementById(name).value;
            arrayPasos.push(data);
        }
    }
    actArrayPasos();

    function ctrlPasos(){
        var container = document.getElementById("pasos");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<numPasos;i++){
            var newDiv = document.createElement('div');
            newDiv.className += "form-group";
            newDiv.id = "div_paso" + (i+1);
            container.appendChild(newDiv);

            var newLabel = document.createElement('label');
            newLabel.className += "mr-2";
            newLabel.innerHTML = "Paso " + (i+1) + ":";
            newLabel.name = "image" + i;
            newDiv.appendChild(newLabel);

            var input = document.createElement("textarea");
            input.className += "form-control";
            input.name = "paso" + (i+1);
            input.id = "id_paso" + (i+1);
            input.rows = "2";
            input.required = 'required';
            if(arrayPasos[i] == undefined){
                input.value = "";
            }else{
                input.value = arrayPasos[i];
            }
            newDiv.appendChild(input);
            //newDiv.appendChild(document.createElement("br"));
        }
    }

    var arrayIngredientes = [];
    function actArrayIngredientes(){
        arrayIngredientes = [];
        var name = ""
        for(i=0; i<numIng; i++){
            name = "id_ingrediente"+(i+1);
            var data = document.getElementById(name).value;
            arrayIngredientes.push(data);
        }
    }
    actArrayIngredientes();

    function ctrlIngredientes(){
        var container = document.getElementById("ingrediente");
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }
        for (i=0;i<numIng;i++){
            var newDiv = document.createElement('div');
            newDiv.className += "form-group";
            newDiv.id = "div_ingrediente" + (i+1);
            container.appendChild(newDiv);

            var input = document.createElement("input");
            input.className += "form-control text-center";
            input.name = "ingrediente" + (i+1);
            input.id = "id_ingrediente" + (i+1);
            input.placeholder = "Ingrediente" + (i+1);
            input.rows = "1";
            input.required = 'required';
            if(arrayIngredientes[i] == undefined){
                input.value = "";
            }else{
                input.value = arrayIngredientes[i];
            }
            newDiv.appendChild(input);
            //newDiv.appendChild(document.createElement("br"));
        }
    }
</script>
{% endblock %}

VID/recetario/templates/explorar.html
{% extends 'base.html' %}

{% block content %}
<div class="row m-5">
  {% for element in expReceta %}
    <div class="card float-left" style="width: 18rem;">
      <img src="{{ MEDIA_URL }}{{ element.imagenMuestra }}" class="card-img-top" height="200px" width="200px"alt="...">
      <div class="card-body" style="background-color: #249E16;">
        <h5 class="card-title text-white" name='nombreReceta' type="text">{{ element.nombre }}</h5>
        <p class="card-text text-white">{{ element.descripcion }}</p>
        <a href="{% url 'mostrarReceta' element.id %}" class="btn btn-light float-right">Ver receta</a>
      </div>
    </div>
    {% endfor %}
    
{% endblock %}
